- year: "2025"
  role: "Co-Organizer"
  event: "Responsible Speech & Audio Generative AI"
  link: "https://codecfake.github.io/RespSA-GenAI/"
  context: "Special Session at IEEE ASRU 2025"
  selected: true

- year: "2024"
  role: "Technical Committee"
  event: "Codec-SUPERB Challenge"
  link: "https://codecsuperb.github.io/"
  context: "Special Session at IEEE SLT 2024"
  selected: true

- year: "2023 - Now"
  role: "Reviewer"
  all_event: "AAAI, ICML, NeurIPS, ACL, EMNLP, COLM, ICASSP, INTERSPEECH, IEEE ASRU, IEEE SLT, COLING, MLSP, IJPRAI"
  event: "AAAI, ICML, NeurIPS, ACL, EMNLP, COLM, ICASSP, ICME, INTERSPEECH, ASRU, SLT, COLING"
  selected: true
